using Avalonia.Controls;
using Avalonia.Interactivity;
using Avalonia.Input; // For TappedEventArgs if needed, DoubleTapped uses RoutedEventArgs
using BasicBlockChain.AvaloniaUI.Models;
using BasicBlockChain.AvaloniaUI.Services;
using BasicBlockChain.Core;
using System; // For DateTime, AppContext
using System.Linq; // For OrderBy
using System.ComponentModel; // For WindowClosingEventArgs

namespace BasicBlockChain.AvaloniaUI // Adjusted namespace
{
    public partial class MainWindow : Window
    {
        private readonly BlockChainService _blockChainService;

        // Fields for UI controls are generated by Avalonia based on x:Name attributes.
        // No need to declare them explicitly here if x:Name is used in XAML.
        // e.g., this.FromTextBox will be available if <TextBox x:Name="FromTextBox" ... /> exists.

        public MainWindow()
        {
            InitializeComponent();

            _blockChainService = new BlockChainService();
            _blockChainService.InitBlockChain(AppContext.BaseDirectory); 

            // MinerNameTextBox is generated by the source generator
            if (this.MinerNameTextBox != null) 
            {
                 this.MinerNameTextBox.Text = _blockChainService.MinerName;
            }

            // Attach event handlers programmatically
            // Assumes buttons and listbox are named in XAML e.g. x:Name="AddTransactionButton"
            if (this.FindControl<Button>("AddTransactionButton") is Button addTransactionButton)
                addTransactionButton.Click += AddTransactionButton_Click;
            
            if (this.FindControl<Button>("MineButton") is Button mineButton)
                mineButton.Click += MineButton_Click;

            if (this.FindControl<Button>("ClearFromButton") is Button clearFromButton)
                clearFromButton.Click += ClearFromButton_Click;

            if (this.FindControl<Button>("ClearToButton") is Button clearToButton)
                clearToButton.Click += ClearToButton_Click;

            if (this.FindControl<Button>("ClearAmountButton") is Button clearAmountButton)
                clearAmountButton.Click += ClearAmountButton_Click;
            
            if (this.FindControl<ListBox>("UsersListBox") is ListBox usersListBox)
                usersListBox.DoubleTapped += UsersListBox_DoubleTapped;
            
            this.Closing += MainWindow_Closing;

            Lists_Update();
        }

        private void Lists_Update()
        {
            var blockChain = _blockChainService.GetBlockChain();
            // Controls are accessed directly by their x:Name (e.g., this.TransactionsListBox)
            if (blockChain == null || this.TransactionsListBox == null || this.PendingTransactionsListBox == null || this.UsersListBox == null) return;

            this.TransactionsListBox.Items.Clear();
            if (blockChain.Chain != null)
            {
                foreach (Block block in blockChain.Chain.OrderByDescending(b => b.Index))
                {
                    if (block.Transactions != null)
                    {
                        foreach (Transaction transaction in block.Transactions)
                        {
                            this.TransactionsListBox.Items.Add(FormatTransaction(transaction));
                        }
                    }
                }
            }

            this.PendingTransactionsListBox.Items.Clear();
            if (blockChain.PendingTransactions != null)
            {
                foreach (Transaction transaction in blockChain.PendingTransactions)
                {
                    this.PendingTransactionsListBox.Items.Add(FormatTransaction(transaction));
                }
            }

            this.UsersListBox.Items.Clear();
            if (blockChain.Users != null)
            {
                foreach (string user in blockChain.Users.OrderBy(u => u))
                {
                    long amount = blockChain.GetMicroCoinBalance(user);
                    this.UsersListBox.Items.Add(new Wallet { User = user, Amount = amount });
                }
            }
        }

        private string FormatTransaction(Transaction transaction) // Renamed from Transaction_ToString
        {
            string sender = transaction.Sender ?? "COINBASE (Reward)";
            // Ensure Receiver is not null for display, though it shouldn't be for normal transactions
            string receiver = transaction.Receiver ?? "N/A"; 
            return $"{transaction.Date:yyyy-MM-dd HH:mm:ss} - {sender} -> {receiver} : {transaction.MicroCoinAmount}";
        }

        private void AddTransactionButton_Click(object? sender, RoutedEventArgs e)
        {
            // Controls are accessed directly by their x:Name
            if (this.FromTextBox == null || this.ToTextBox == null || this.AmountNumericUpDown == null ||
                string.IsNullOrEmpty(this.FromTextBox.Text) || string.IsNullOrEmpty(this.ToTextBox.Text))
            {
                Console.WriteLine("Debug: Add transaction fields not filled or controls not found.");
                return;
            }
            
            var blockChain = _blockChainService.GetBlockChain();
            if (blockChain == null) return;

            // AmountNumericUpDown.Value is decimal?
            if (this.AmountNumericUpDown.Value.HasValue && this.AmountNumericUpDown.Value.Value > 0)
            {
                long amount = (long)this.AmountNumericUpDown.Value.Value; // Cast decimal to long
                blockChain.AddTransaction(new Transaction(this.FromTextBox.Text, this.ToTextBox.Text, amount, DateTime.UtcNow));
                
                this.FromTextBox.Text = string.Empty;
                this.ToTextBox.Text = string.Empty;
                this.AmountNumericUpDown.Value = 0; // Reset
                Lists_Update();
            }
            else
            {
                Console.WriteLine("Debug: Amount must be greater than zero.");
            }
        }

        private void MineButton_Click(object? sender, RoutedEventArgs e)
        {
            if (this.MinerNameTextBox == null || string.IsNullOrEmpty(this.MinerNameTextBox.Text))
            {
                 Console.WriteLine("Debug: Miner name not set or control not found.");
                return;
            }
            
            var blockChain = _blockChainService.GetBlockChain();
            if (blockChain == null) return;

            _blockChainService.MinerName = this.MinerNameTextBox.Text;
            blockChain.ProcessPendingTransactions(DateTime.UtcNow, _blockChainService.MinerName);
            Lists_Update();
        }

        private void ClearFromButton_Click(object? sender, RoutedEventArgs e)
        {
            if (this.FromTextBox != null) this.FromTextBox.Text = string.Empty;
        }

        private void ClearToButton_Click(object? sender, RoutedEventArgs e)
        {
            if (this.ToTextBox != null) this.ToTextBox.Text = string.Empty;
        }

        private void ClearAmountButton_Click(object? sender, RoutedEventArgs e)
        {
            if (this.AmountNumericUpDown != null) this.AmountNumericUpDown.Value = 0;
        }

        private void UsersListBox_DoubleTapped(object? sender, RoutedEventArgs e) 
        {
            if (this.UsersListBox?.SelectedItem is Wallet selectedWallet && selectedWallet.User != null)
            {
                if (this.FromTextBox != null && string.IsNullOrEmpty(this.FromTextBox.Text))
                {
                    this.FromTextBox.Text = selectedWallet.User;
                }
                else if (this.ToTextBox != null && string.IsNullOrEmpty(this.ToTextBox.Text))
                {
                    this.ToTextBox.Text = selectedWallet.User;
                }
            }
        }

        private void MainWindow_Closing(object? sender, WindowClosingEventArgs e) 
        {
            if (this.MinerNameTextBox != null) 
            {
                 _blockChainService.MinerName = this.MinerNameTextBox.Text ?? _blockChainService.MinerName;
            }
            _blockChainService.SaveBlockChain();
        }
    }
}
